### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by dragonee** [makimo/style-guide#14]
With links to documents and desired order to read them.

**Comment by IwoHerka** [comment]
@dragonee I have a few ideas about what sorts of document I would like to have, but just to be sure we'are on the same page, what would you like to see?

**Comment by dragonee** [comment]
For now - how the document is structured, e.g.

(What it is)
- a set of recommendations for consinstent coding throughout the team
(What it contains and reading order)

All other things are nice to have but not essential right now.
