### ISSUE TITLE
Documentation line width

### ISSUE THREAD

**Issue by Struchu** [makimo/style-guide#19]
I would strongly recommend following the convention of keeping documentation lines (docstrings, comments for modules, functions, methods, classes etc.) shorter than 72 characters.

**Comment by IwoHerka** [comment]
This is what we have for Python:

> Try to fit 70–80 character if possible. If readability is at risk, aim for 90/100. Generally, if you're going over 100 you're doing something wrong. Consider configuring your text-editor to mark columns 70, 80 and 90.

What are your thoughts on that?

**Comment by Struchu** [comment]
I know, but the 72 line width should target only comment sections (not code itself). It's much more readable if the natural language describing a function is shorter than the code itself.
