### ISSUE TITLE
Blank lines should be marked as necessary but not sufficient

### ISSUE THREAD

**Issue by dragonee** [makimo/style-guide#3]
https://github.com/makimo/style-guide/blob/master/python_syntax.md#6-blank-lines

Currently, the intention can be ambiguous whether this article speaks about necessary, sufficient or allowed blank lines. The answer is necessary but not sufficient, because by following the rules to the letter you'll come up with this:

```
if a:
    return True
b = x or None
if b is not None:
    do_work()
else:
    do_some_other_work()
return False
```

**Comment by IwoHerka** [comment]
To be honest I didn't know we are going that deep into specification. I would like that but didn't think it would be looked upon too kindly (too many rules).

I will fill in the blanks then.
