### ISSUE TITLE
Proposal: sections and articles

### ISSUE THREAD

**Issue by dragonee** [makimo/style-guide#4]
I do not know, where the future will lead us, but what I envision is that we'll someday do one of two things:

- refer to specific parts of this guide
- write tools that will refer to specific parts of this guide

So it would be nice to have it constructed in a similar fashion as legal documents are. I'm ambivalent as to the terminology and symbols used, but in short I feel we need three levels:

- a path to the document (`git.md`) or spoken reference uniquely pointing to the document ("Git convention") 
- a section (1. Something)
- an article (1.3 Article)

What I would like not to do is to make multi-levels (like 1.3.5.1), but try to adhere to the above structure (if really necessary, then you can add a), b), c) points to the article).

This also prevents us from being overly complicated in our reasoning. If we need behaviour trees when writing a coding style, that should be a signal that maybe there is an issue to discuss.

**Comment by IwoHerka** [comment]
We are already doing that (see `git.md`). In `python_syntax` there was simply no opportunity do that yet.
