### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by dragonee** [makimo/style-guide#5]
What is the logic behind using `###` or `##` at the top of a file instead of `#`?

**Comment by IwoHerka** [comment]
I simply find `#` too big. The contrast is unpleasant for me to look at. I will change it if you wish.

**Comment by dragonee** [comment]
Then, let us choose one from two:
- `#` title `##` section `###` article
- `##` title `###` section `####` article

The second one is nice if we ever try thinking of merging MD files together in a form of a booklet. So how about this one?

**Comment by IwoHerka** [comment]
My vote goes for the second one. :)

**Comment by dragonee** [comment]
Cool, let's go with that. I'll change `django.md` in a related pull request.
